import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("open port dialog refreshes state without losing scroll or control focus", async () => {
  const source=await readFile("src/cisco-catalyst-switch-card.js","utf8");
  assert.match(source,/scheduleDialogRefresh\(force=false, returnFocusControl=null\)/);
  assert.match(source,/const stateKey=JSON\.stringify\(port\)/);
  assert.match(source,/stateKey===this\._dialogStateKey/);
  assert.match(source,/this\._dialogStateKey=JSON\.stringify\(port\)/);
  assert.match(source,/scheduleDialogRefresh\(true,returnFocusControl\)/);
  assert.match(source,/const scrollTop=dialog\.scrollTop/);
  assert.match(source,/preserveDialogState:true/);
  assert.match(source,/dialog\.scrollTop=scrollTop/);
  assert.match(source,/focusedControl/);
  assert.match(source,/Focus rule: an async action restores focus to its initiating logical control/);
  assert.match(source,/returnFocusControl \?\? dialog\.querySelector\(":focus"\)/);
  assert.match(source,/toggleEntity\(port\.entityIds\.admin,port\.adminEnabled,"admin"\)/);
  assert.match(source,/toggleEntity\(port\.entityIds\.poe,port\.poeEnabled,"poe"\)/);
  assert.match(source,/if\(!preserveDialogState\) requestAnimationFrame/);
  assert.match(source,/this\._controlPendingEntities\?\?=new Set\(\)/);
  assert.match(source,/pending\.has\(entityId\)/);
  assert.match(source,/pending\.add\(entityId\)/);
  assert.match(source,/pending\.delete\(entityId\)/);
  assert.match(source,/Working…/);
  assert.match(source,/!this\.shadowRoot\?\.activeElement\?\.matches\?\.\("\[data-port\]"\)/);
  assert.match(source,/addEventListener\("pointerdown"/);
  assert.match(source,/event\.detail===0/);
  assert.match(source,/handlePortKeydown\(event,el\)/);
  assert.match(source,/\["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","Home","End"\]/);
  assert.match(source,/getBoundingClientRect\(\)/);
  assert.match(source,/current\.closest\("\.grid"\)/);
  assert.match(source,/event\.ctrlKey/);
  assert.match(source,/const sameColumn=/);
  assert.match(source,/const focusedPort = this\.shadowRoot\.activeElement\?\.dataset\?\.port \?\? null/);
  assert.match(source,/CSS\.escape\(focusedPort\)/);
  assert.match(source,/dialog\.onkeydown/);
  assert.match(source,/ArrowUp","ArrowDown","PageUp","PageDown","Home","End/);
  assert.match(source,/dialog\.scrollBy/);
  assert.match(source,/dialog\.scrollTo/);
  assert.match(source,/event\.key==="Escape"/);
  assert.match(source,/requestAnimationFrame\(\(\)=>this\.shadowRoot\.querySelector/);
  assert.match(source,/dialog\.close\(\);this\.render\(\);/);
});
